### ISSUE TITLE
Not compatible with current prom-client API

### ISSUE THREAD

**Issue by dobesv** [pbadenski/bull-prom#2]
The current version of `prom-client` requires the parameters to `Guage` to be an object specifying the information as a single argument instead of three arguments.

**Comment by pbadenski** [comment]
Could you send a pull request? I don't have the capacity to add this feature at the moment...

**Comment by dobesv** [comment]
Eh, no I just reimplemented the metrics.  I don't have time, either.  I guess this issue can at least be here for reference.
